### ISSUE TITLE
SetVehicleDoorsLocked Should be 2 not 4

### ISSUE THREAD

**Issue by Vampurica** [ESX-PUBLIC/esx_vehiclelock#19]
Per the Native Reference if SetVehicleDoorsLocked is set to 4, someone can still enter the vehicle and not exit. It should be setting the doors to 2 instead, which entirely locks the vehicle.

**Comment by MarchTala** [comment]
> Per the Native Reference if SetVehicleDoorsLocked is set to 4, someone can still enter the vehicle and not exit. It should be setting the doors to 2 instead, which entirely locks the vehicle.

I agree on this, I tried and it won't break the window of the car. cheeerz (y)
