### ISSUE TITLE
Issues with persistency 

### ISSUE THREAD

**Issue by benzon** [ESX-PUBLIC/esx_vehiclelock#2]
Not sure if this is intended behaviour.

But when using lock status 4 you can break the window and get in to the car, but you are then trapped inside the car after, and cant get out.

Noticed the work around, think you need to run that all the time, to make sure lock status 4 aint going to trap ppl inside the car.

Setting the Wait to 2000ms lets the animation of trying to open the door run, before clearing ped task.

In general currently the work around aint doing a lot, it runs for 100ms and after that turns it self off, dont get the idea behind this tho.

`Citizen.CreateThread(function()
	local vehicle

	while true do
		Citizen.Wait(2000)
		local playerPed = PlayerPedId()

		local vehicle = GetVehiclePedIsTryingToEnter(playerPed)

		if DoesEntityExist(vehicle) then
			local lockStatus = GetVehicleDoorLockStatus(vehicle)

			if lockStatus == 4 then
				ClearPedTasks(playerPed)
			end
		end
	end
end)`

**Comment by p3dr0augusto** [comment]
Have you found any other way? Because it isn't fixed yet...

**Comment by TKLeuPT** [comment]
Hi guys, you just need to modify the script, when it uses lock 4 change it to 2, replace the following lines

line 42
if lockStatus == 2 then

line 76
SetVehicleDoorsLocked(vehicle, 2)

line 80
elseif lockStatus == 2 then -- locked
Enjoy, and have fun! :)
