### ISSUE TITLE
Can't lock emergency vehicles

### ISSUE THREAD

**Issue by MeerkatRS** [ESX-PUBLIC/esx_vehiclelock#4]
Any idea why the only vehicles we can't lock are emergency vehicles?

**Comment by CruelAlpha** [comment]
+1

**Comment by RichardBiggs** [comment]
+1 I can lock owned emergency vehicles while inside but unable to from the exterior.

**Comment by RichardBiggs** [comment]
I decided to add an option in the police job menu to unlock the vehicle without the delay included in the lockpick option. So when a police officer is in an owned police vehicle they can lock it, still exit, and the car remains locked. To re-enter they open the job menu and hit "unlock police vehicle" and it lets them back in. Not an optimal solution but better than nothing for now.

**Comment by taysupra** [comment]
+1

**Comment by osprey1337** [comment]
+1 Have the same issue...
