### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by FRANkiller13** [ESX-PUBLIC/esx_vehiclelock#6]
I put the script and nothing doesnt work... withou any error...is anyone have this problem ?

**Comment by RichardBiggs** [comment]
Are you trying to lock a vehicle you own? Specifically a car that is in your sql database in table "owned_table" (that you imported from esx_vehicleshop) and "owner"= your steamhex I.E. steam:110000xxxxxxxxx

**Comment by FRANkiller13** [comment]
Yeah im trying to lock/unlock my car and doesnt work without errors or something else

![Untitled](https://user-images.githubusercontent.com/5957308/55773724-a028c280-5a9a-11e9-88ee-b82950c460a9.png)

**Comment by RichardBiggs** [comment]
I would suggest installing it again. I have it installed currently and with the exception of not being able to locked owned emergency vehicles from the exterior everything works as it should. If you reinstall and still have issues, verify the keybind is set to the key you are using or even change it to another key according to the fiveM documentation to test if maybe another script is blocking input of that specific key.
